name: upload-to-google-cloud-storage

on:
  workflow_call:
    inputs:
      aab-artifact-name:
        description: AAB Artifact Name.
        required: true
        type: string
      version-code:
        description: Version Code.
        required: true
        type: string
      bucket-name:
        description: GCS Bucket Name.
        required: true
        type: string
      environment:
        description: Deployment Environment.
        required: true
        type: string
      service-account-name:
        description: GCP Service Account Name.
        required: false
        type: string
        default: github-action-1024803243
      project-id:
        description: GCP Project ID.
        required: false
        type: string
      project-number:
        description: GCP Project Number.
        required: false
        type: string
    secrets:
      SLACK_WEBHOOK_URL:
        description: SLACK_WEBHOOK_URL
        required: true

jobs:
  upload-to-gcs:
    name: Upload AAB to Google Cloud Storage
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Setup GCloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          workload_identity_provider: 'projects/${{ inputs.project-number }}/locations/global/workloadIdentityPools/github-pool/providers/github-provider'
          service_account: '${{ inputs.service-account-name }}@${{ inputs.project-id }}.iam.gserviceaccount.com'

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.aab-artifact-name }}

      - name: Download Mapping Artifact
        uses: actions/download-artifact@v4
        with:
          name: mapping

      - uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.merged-native-libs-symbols-artifact-name }}

      - name: LS AAB File
        run: ls -la

      - name: Upload AAB to GCS
        run: |
          gsutil cp ./${{ inputs.aab-artifact-name }} gs://${{ inputs.bucket-name }}/releases/${{ inputs.environment }}/app-${{ inputs.version-code }}.aab

      - name: Upload Mapping to GCS
        run: |
          gsutil cp ./mapping.txt gs://${{ inputs.bucket-name }}/releases/${{ inputs.environment }}/mapping-${{ inputs.version-code }}.txt

      - name: Upload Merged Native Libs Symbols to GCS
        run: |
          gsutil cp -r ./symbols.zip gs://${{ inputs.bucket-name }}/releases/${{ inputs.environment }}/symbols-${{ inputs.version-code }}.zip

      - if: ${{ failure() }}
        name: The job has failed
        uses: rtCamp/action-slack-notify@v2.2.0
        env:
          SLACK_MESSAGE: "Push AAB :android: assets to Google Cloud Storage for `${{ github.event.repository.name }}` failed :x:."
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}